name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"
          cache: true

      - name: Build release binaries
        run: |
          make build
          # Create release archives
          cd bin
          tar -czf pocketbase-sdk-linux-amd64.tar.gz pocketbase example
          zip pocketbase-sdk-linux-amd64.zip pocketbase example

      - name: Create or Update Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            ## Changes

            See [CHANGELOG.md](CHANGELOG.md) for details.

            ## Installation

            ```bash
            go get github.com/Forty2Co/pocketbase@${{ github.ref_name }}
            ```
          draft: false
          prerelease: false
          files: |
            ./bin/pocketbase-sdk-linux-amd64.tar.gz
            ./bin/pocketbase-sdk-linux-amd64.zip
